### PR TITLE
Uniformize domain builders

### LINKED ISSUE #761: Loading a game crashes actor HUD

### PR DESCRIPTION
**Pull request by OrenjiAkira**
Refactors actor/body save/load methods, which closes #761 

This centralizes actor and body generation in the builders, and revamps route's `makeActor` and `makeBody` methods. Adjust rest of code accordigly.

Also this is necessary for #451 , as it introduces the "traits" spec on the actor, which will specify their base abilities.

### CODE REVIEW

File: game/domain/builders/body.lua [hunk 1]
```diff
@@ -1,11 +1,17 @@
...
-function BUILDER.build(idgenerator, species, i, j)
+function BUILDER.buildState(idgenerator, species, i, j)
   return {
     id = idgenerator.newID(),
     specname = species,
     damage = 0,
+    upgrades = {
+      DEF = 100,
+      VIT = 100,
+    },
```
Comment (Kazuo256) [inline game/domain/builders/body.lua]: This doesn't exist anymoe.
